version: '3.8'

services:
  whisper-transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount for persistent storage of models (optional)
      - whisper_models:/root/.cache/whisper
      # Mount for temporary files
      - ./temp:/tmp/whisper_temp
      # Mount for uploads (development only)
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    networks:
      - whisper-network

  # Optional: Redis for caching (for future features)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - whisper-network
    profiles:
      - cache

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - whisper-transcriber
    restart: unless-stopped
    networks:
      - whisper-network
    profiles:
      - production

volumes:
  whisper_models:
    driver: local
  redis_data:
    driver: local

networks:
  whisper-network:
    driver: bridge

# Development override
# Create docker-compose.override.yml for development settings:
#
# version: '3.8'
# services:
#   whisper-transcriber:
#     volumes:
#       - .:/app
#     environment:
#       - STREAMLIT_SERVER_FILE_WATCHER_TYPE=auto
#     command: streamlit run main.py --server.fileWatcherType auto